<a href="https://colab.research.google.com/github/987Radhu/Data-analyst/blob/data-analyst/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [6]:
list1=[1,2,3,4,5]
list2=[1,2,3,4,5]

list3=list1+list2
print(list3)

arr1=np.array(list1)
arr2=np.array(list2)

#print("array1",arr1)
res=arr1+arr2
print("result",res)


[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
result [ 2  4  6  8 10]


In [8]:
cont=np.concatenate((arr1,arr2))
cont

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [28]:
arr= np.array([1,2,3,4,5,6,7,8,9,10,11,12])
new_array=arr.reshape(3,4)
new_array


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
arr = np.array([[1, 2, 3, 4],
[5, 2, 4, 2],
[1, 2, 0, 1]])
newarr = arr.reshape(2, 3, 2)
print ("Original array:\n", arr)
print("---------------")
print ("Reshaped array:\n", newarr)

Original array:
 [[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
---------------
Reshaped array:
 [[[1 2]
  [3 4]
  [5 2]]

 [[4 2]
  [1 2]
  [0 1]]]


In [30]:
flat=arr.flatten()

print(arr)
print(flat)

[[1 2 3 4]
 [5 2 4 2]
 [1 2 0 1]]
[1 2 3 4 5 2 4 2 1 2 0 1]


In [39]:
arr1=np.arange(14)
print(arr1)
new_array2=np.split(arr1,7)
print(new_array2)

arr3=arr1.dtype
print(arr3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13]
[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9]), array([10, 11]), array([12, 13])]
int64
